//
// Created by alg on 21/11/20.
//

#ifndef MULTIAGENTCIRCLEMAP_MULTIROBOTMAPPER_H
#define MULTIAGENTCIRCLEMAP_MULTIROBOTMAPPER_H


class MultiRobotMapper {

};


#endif //MULTIAGENTCIRCLEMAP_MULTIROBOTMAPPER_H
